dist: xenial

notifications:
  slack:
    on_success: always
services:
  - postgresql
addons:
  - postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - psql -U postgres -c "DROP DATABASE \"test_decide\""
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
#script:
#  - cd decide
#  - python manage.py test census
#deploy:
#  provider: heroku
#  app:  alorodlla-egc-examen
#  strategy: git
#  api_key: $HEROKU_AUTH_TOKEN
